version: '3'

services:
    web:
        image: nginx:latest
        container_name: brg_meetup_web
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - .:/brg_meetup
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        restart: always

    php:
        container_name: brg_meetup_php
        build:
            context: ./docker/php
        depends_on:
            - composer
            - mariadb
        volumes:
            - .:/brg_meetup
        env_file: meetup.env
        restart: always

    mariadb:
        container_name: brg_meetup_mariadb
        build:
            context: ./docker/mariadb
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        env_file: meetup.env
        restart: always

    db_migration:
        container_name: brg_meetup_db_migration
        build:
            context: ./docker/db_migration
        depends_on:
            - mariadb
        volumes:
            - .:/brg_meetup
        restart: 'no'

    composer:
        container_name: brg_meetup_composer
        build:
            context: ./docker/composer
        command: install --ignore-platform-reqs
        volumes:
            - .:/app
        restart: 'no'
